config/routes.rb
Rails.application.routes.draw do

  resources :exams

  namespace :home do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end



  devise_for :users
  devise_for :admins


  root 'home/welcome#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exam.rb
class Exam < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :exam
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :authenticate_user!

  def index
    @exams = Exam.all
  end

  def new
    @exam = Exam.new
    10.times { @exam.questions.build } 
  end

  def create
    @exam = Exam.new(exam_params)
    if @exam.save
      redirect_to @exam, notice: 'Compilado criado com sucesso!'
    else
      render :new
    end
  end

  def show
    @exam = Exam.find(params[:id])
  end

  private

  def exam_params
    params.require(:exam).permit(:name, :university, questions_attributes: [:id, :question_text, :answer])
  end

end

app/controllers/home/welcome_controller.rb
class Home::WelcomeController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home/welcome_helper.rb
module Home::WelcomeHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!-- <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %> -->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/welcome/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Area Administrativa</h1>
  
  <p><%= link_to 'Logoff', destroy_admin_session_path, data: { "turbo-method": :delete } %></p>
</div>

app/views/exams/index.html.erb
  <div class="flex-col">
    <h1 class="text-center font-bold text-4xl">Lista de Compilados</h1>
    
    
      <ul>
        <% @exams.each do |exam| %>
          <div class="flex-col  text-white bg-pink-800 p-6 rounded-3xl shadow-md w-full m-4">          
            <%= link_to exam.name, exam_path(exam) %>        
          </div>
        <% end %>
      </ul>
    
    
    <%= link_to 'New Exam', new_exam_path , class: "flex bg-pink-800 w-full text-white p-6 rounded-3xl border rounded-3x1 m-4 hover:bg-pink-950 hover:font-bold cursor-pointer" %>
  </div>

app/views/exams/new.html.erb
<div class="flex-col  text-white bg-pink-800 p-6 rounded-3xl shadow-md w-full">
  <h1 class="text-center font-bold text-4xl">New Exam</h1>
  
  <%= form_with(model: @exam, local: true) do |form| %>
    <fieldset class="border-2 p-2 pb-4 rounded-lg m-4">
      <div class="flex flex-row gap-6">
        <div class="basis-1/2">
          <%= form.label :university %>
          <%= form.text_field :university, class: "basis-1/2 w-full border rounded-2xl p-2 text-black" %>
        </div>
        <div class="basis-1/2">
          <%= form.label :name %>
          <%= form.text_field :name, class: "basis-1 w-full border rounded-2xl p-2 text-black"  %>
        </div>
      </div>
    </fieldset>  
    <%= form.fields_for :questions do |question_form| %>
    <fieldset class="border-2 p-2 pb-4 rounded-lg m-4">
      <div>
        <%= question_form.label :question_text %>
        <%= question_form.text_area :question_text, class: "w-full border rounded-2xl p-2 text-black" %>
      </div>
  
      <div>
        <%= question_form.label :answer %>
        <%= question_form.text_area :answer, class: "w-full border rounded-2xl p-2 text-black" %>
      </div>
    </fieldset> 
    <% end %>
  
    <div>
      <%= form.submit 'Create Exam', class: "flex  border rounded-lg p-4 m-4 hover:bg-pink-950 hover:font-bold cursor-pointer" %>
    </div>
  <% end %>
</div>

app/views/exams/show.html.erb
<div class="flex-col  text-white bg-pink-800 p-6 rounded-3xl shadow-md w-full">
  <h1 class="text-center font-bold text-4xl">Compilado</h1>
  <fieldset class="border-2 p-2 pb-4 rounded-lg m-4">
    <p><strong>Name:</strong> <%= @exam.name %></p>
    <p><strong>University:</strong> <%= @exam.university %></p>
  </fieldset>
  
  <h2 class="text-center font-bold text-4xl">Questions</h2>
  <ul>
    <% @exam.questions.each do |question| %>
    <fieldset class="border-2 p-2 pb-4 rounded-lg m-4">
      <li>
        <p class="p-2"><strong>Question:</strong> <%= question.question_text %></p><br>
        <strong>Answer:</strong> <%= question.answer %>
      </li>
    </fieldset>
    <% end %>
  </ul>
  
  <%= link_to 'Back', exams_path %>
</div>

app/views/home/welcome/index.html.erb
<div class="flex p-2 justify-center content-center overflow-hidden">
  <div>
    <p>
      Bem vindo(a) ao,
    </p>
    <h1 class="text-5xl font-bold">
      Compilados
    </h1>
    <p>
      Contribua com seu compilado
    </p>   

    <button class="bg-pink-800 p-3 font-bold text-white rounded-lg hover:scale-105"><%= link_to 'Contribua', new_exam_path %></button>
  </div>
  <%= image_tag('img_home', class: 'w-auto h-auto') %>
  
</div>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compiled</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="overflow-hidde">
    <%= render 'shared/nav' %>
    <h1>Area Administrativa</h1>
    <main class="flex justify-center min-h-full p-10">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compiled</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/nav' %>
    <main class="container mx-auto mt-28 px-1 flex">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compiled</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="flex flex-col min-h-screen overflow-hidde ">
    <%= render 'shared/nav' %>
    <main class="flex my-14 justify-center p-8">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Compiled</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="overflow-hidde">
    <%= render 'shared/nav' %>
    <h1>Area de usuarios</h1>
    <main class="flex justify-center min-h-full p-10">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="fixed bottom-0 left-0 w-full bg-pink-800 text-center text-white p-4">
 <blockquote>Pagina criada para fins de estudo</blockquote>
</div>

app/views/shared/_nav.html.erb
<div class="flex p-4 justify-between content-center items-center bg-pink-800 text-white sticky top-0">

    <h3 class="font-bold text-3xl">Compilados</h3>
 
  <ul class="flex gap-8 ">
    <li class="hover:font-bold hover:scale-125 cursor-pointer">
      <%= link_to 'Home', home_welcome_index_path %>
    </li>
    <li class="hover:font-bold hover:scale-125 cursor-pointer">
      <%= link_to 'Compilados', exams_path %>
    </li>
    <li class="hover:font-bold hover:scale-125 cursor-pointer">Bilioteca</li>
    <% if user_signed_in? %> <!-- Verifica se o usuário está logado -->
      <li class="hover:font-bold hover:scale-125 cursor-pointer">
        <%= link_to 'Logoff', destroy_user_session_path, data: { "turbo-method": :delete } %>
      </li>
    <% else %>
      <li class="hover:font-bold hover:scale-125 cursor-pointer">
        <%= link_to 'Login', users_backoffice_welcome_index_path %>
      </li>
    <% end %>
    <% if admin_signed_in? %> <!-- Verifica se o usuário está logado -->
      <li class="hover:font-bold hover:scale-125 cursor-pointer">
        <%= link_to 'Logoff', destroy_admin_session_path, data: { "turbo-method": :delete } %>
      </li>
    <% else %>
      <li class="hover:font-bold hover:scale-125 cursor-pointer">
        <%= link_to 'admin', admins_backoffice_welcome_index_path %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name)  %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users_backoffice/welcome/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Area de Usuarios</h1>
  
  <p><%= link_to 'Logoff', destroy_user_session_path, data: { "turbo-method": :delete } %></p>
</div>